#ifndef GENERATESHAREDLL_GLOBAL_H
#define GENERATESHAREDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERATESHAREDLL_LIBRARY)
#  define GENERATESHAREDLL_EXPORT Q_DECL_EXPORT
#else
#  define GENERATESHAREDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERATESHAREDLL_GLOBAL_H
